# -*- coding: utf-8 -*-
"""lastAttempt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XtGxe-MQvO-BNbw4UGmG0St4qG_bIApz
"""

def custom_mean(data):
  return sum(data) / len(data)